version: "3.7"
services:


  backend:
    container_name: backend
    command: ["bash", "scripts/backend-start.sh"]
    build:
      context: .
      dockerfile: backend.dockerfile
    restart: on-failure
    env_file:
      - ./.env
    ports:
       - 8000:8000
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    networks:
      - project_auth


  db:
    container_name: db
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    restart: unless-stopped
    volumes:
      - db-posts-data:/var/lib/postgresql/data
    ports:
      - 5435:5432
    networks:
      - project_auth


  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6371:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "50m"
    networks:
      - project_auth


volumes:
  db-posts-data:


networks:
  project_auth:
    driver: bridge
